//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyCeeper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costs
    {
        public int Cost_Id { get; set; }
        public System.DateTime Date_time { get; set; }
        public string Categoty { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
        public decimal Price { get; set; }
        public string User_name { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
