//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyCeeper.Model_EDM_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public int Id { get; set; }
        public double Price { get; set; }
        public string Comment { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTime { get; set; }
        public Category Category { get; set; }
        public string User { get; set; }
    
        public virtual User User1 { get; set; }
    }
}
